It
seems
that
my
issue
was
using
multiple
zmq
contexts
over
different
processes
.
While
the
PyZMQ
documentation
states
that
the
zmq
context
is
thread-safe
","
I
can
only
assume
it
meant
Python
threads
rather
than
processes
.
This
is
quite
confusing
as
in
C
","
zmq
contexts
are
thread
safe
despite
running
in
a
way
similar
to
the
Python
multiprocessing.Process
.
The
issue
was
solved
by
creating
a
zmq
context
for
each
Process
.
