I'm
trying
to
code
a
dictionary
based
logging
configuration
and
have
been
stumped
by
a
ValueError
that
occurs
when
I
run
the
program
.
I've
stripped
it
down
to
the
essentials
and
the
problem
remains
.
I've
read
the
3.5
docs
","
logging
HOWTO
","
Logging
Cookbook
","
etc.
but
unfortunately
","
the
solution
has
not
presented
itself
.
Any
help
would
be
appreciated
.
Also
","
I'm
only
3
weeks
into
python
so
I
may
just
be
out
of
my
depth
at
this
point
.
Here's
the
code
...
When
run
","
I
receive
the
follow
:
or
sometimes
this
...
I
suspect
that
the
different
errors
may
have
to
do
with
the
sometimes
changing
order
of
the
dictionary
?
